name: Update Submodules
on:
  workflow_dispatch:  # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Update Submodules
        run: |
          git submodule update --remote --force
          git add .
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "Auto-update submodules" || echo "No changes"
          git push
